### PR TITLE
Fix slight issue with includesEntry not properly checking entiries and implement sending compare data to client.

### PR DESCRIPTION
**Pull request by wgaylord**
Fixies the comparing in includes to fully check the entries to tell if they are identical.

### CODE REVIEW

**Comment by wgaylord** [comment]
I am currently running the dev code on the server to check to see if it work as intended. May want to wait until then before merging.

**Comment by wgaylord** [comment]
This PR works correctly from what I can tell. Still waiting on a change to occur to know if it fully works.

**Comment by wgaylord** [comment]
Okay. I can confirm it works properly.

**Review by aaldossari — APPROVED** [review]

**Review by aaldossari — APPROVED** [review]
Looks good

**Review by aaldossari — APPROVED** [review]

**Review by aaldossari — APPROVED** [review]

**Review by aaldossari — APPROVED** [review]

**Review by aaldossari — APPROVED** [review]

**Review by aaldossari — APPROVED** [review]

**Comment by aaldossari** [comment]
Overall it looks good

**Pull request merged**
